### ISSUE TITLE
Refactor resources like dimen or strings.

### ISSUE THREAD

**Issue by gomyk** [gomyk/ToyProjectApp#23]
boiler plate 코드가 리소스부분에 많아서 중복되는 것들 모아서 하드코딩하게 해두었던 부분들 정리해서 좀 묶어주세요
ex)
textsize = "20dp" 
 => 
textsize = "@dimen/textSize_middle"

**Comment by hiasince** [comment]
1차 수정 건 merge되었고, 2차적으로 리뷰 받은 사항, 빼먹은 부분 수정 후 완료 예정

## 리뷰 받은 사항

- [x] color부분 : 색으로 구분 후 의미 맞게 색 부여
- [x] string 부분 : 놓친 부분 추가

## 빼먹은 부분

- [x] popup 관련 설정 놓침
